### ISSUE TITLE
no method for 'pinRead'

### ISSUE THREAD

**Issue by 60-hz** [NullMember/PDFirmata#2]
Under OSX 10.15.4, pd 0.51.4, pdfirmata.osx64 v2.0.0:

When send "pinRead 13" message, the console returns:

pdfirmata: no method for 'pinRead'

**Comment by NullMember** [comment]
After beta stage I've renamed pinRead method to pinState because it's purpose is [reading state of pin, not value of pin](https://github.com/firmata/protocol/blob/master/protocol.md#pin-state-query). If you're trying to read value of pin you can use digitalIn method. It's similiar to analogIn but instead of pin number you should pass port number (for Uno, Port 0 is pin 0-7, Port 1 is pin 8-13, Port 2 is A0-5). 
If reporting (second argument) is non-zero, you will get port values at every update. To disable reporting send zero as second argument. digitalIn will report all values of port, you should extract pin value from it.
To read pin 13 value
[digitalIn 1 1<
|
[pdfirmata]
|
[route digitalIn]
|
[route 1]
|
[>> 5]
|
[& 1]
|
[value of pin 13: $1<
|
[print]

Clearly help file is caused this confusion. I'ts my mistake, sorry about that. Will update it soon.

**Comment by 60-hz** [comment]
Nice, thanks for the clarification!

**Comment by NullMember** [comment]
Help file updated in d86714d571d7901adb7978e2e60fee8ddce27220. Thanks!
